# Generated by Django 4.0.1 on 2022-01-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.CharField(max_length=200)),
                ('risk_owner', models.CharField(max_length=100)),
                ('risk_date', models.DateTimeField(verbose_name='Date Risk was discovered')),
                ('risk_mitigation', models.CharField(max_length=500)),
                ('risk_due_date', models.DateTimeField(verbose_name='Date the risk is expected to be resolved')),
                ('risk_status', models.CharField(max_length=200)),
                ('risk_assignee', models.CharField(max_length=200)),
                ('risk_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_type', models.CharField(max_length=60)),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_register.risks')),
            ],
        ),
    ]
