# Generated by Django 4.0.1 on 2022-01-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
            ],
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
    ]
