# Generated by Django 4.0.1 on 2022-01-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0004_alter_risks_risk_date_alter_risks_risk_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='risk_impact',
            field=models.CharField(choices=[('resources', 'RESOURCES'), ('cost', 'COST'), ('schedule', 'SCHEDULE'), ('scope', 'SCOPE'), ('other', 'OTHER')], default='other', max_length=15),
        ),
    ]
