# Generated by Django 4.0.1 on 2022-01-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0005_risks_risk_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risks',
            name='risk_impact',
            field=models.CharField(choices=[('please select', 'Please select'), ('resources', 'Resources'), ('cost', 'Cost'), ('schedule', 'Schedule'), ('scope', 'Scope'), ('other', 'Other')], default='please select', max_length=15),
        ),
    ]
