# Generated by Django 4.0.1 on 2022-01-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0007_alter_risks_risk_date_alter_risks_risk_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risks',
            options={'verbose_name': 'Project Risks', 'verbose_name_plural': 'Project Risks'},
        ),
    ]
