# Generated by Django 4.0.1 on 2022-01-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0012_remove_projects_project_projects_risks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risks',
            name='risk_rank',
        ),
    ]
