# Generated by Django 4.0.1 on 2022-02-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0013_remove_risks_risk_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risks',
            name='risk_impact',
            field=models.CharField(choices=[('choose a category', 'Choose a category'), ('resources', 'Resources'), ('cost', 'Cost'), ('schedule', 'Schedule'), ('scope', 'Scope'), ('other', 'Other')], default='choose a category', max_length=30),
        ),
    ]
