# Generated by Django 4.0.1 on 2022-02-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0014_alter_risks_risk_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risks',
            name='risk_due_date',
            field=models.DateField(blank=True, default='Pick a due date', null=True),
        ),
    ]
