# Generated by Django 4.0.1 on 2022-02-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0016_remove_projects_risks_projects_risks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='risks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_register.risks'),
        ),
    ]
