# Generated by Django 4.0.1 on 2022-02-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0018_remove_projects_risks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
