# Generated by Django 4.0.1 on 2022-02-07 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('risk_register', '0020_risks_risks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
